[package]
name = "term-colors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4.8"
dioxus = { version = "0.2.3", features = ["ssr"] }
tokio = { version = "1.17.0", features = ["full"] }
